apiVersion: v1
kind: Secret
metadata:
  name: langfuse-encryption-key-secret
type: Opaque
stringData:
  encryptionKey: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-general
type: Opaque
stringData:
  salt: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-nextauth-secret
type: Opaque
stringData:
  nextauth-secret: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-postgresql-auth
type: Opaque
stringData:
  password: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-clickhouse-auth
type: Opaque
stringData:
  password: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-redis-auth
type: Opaque
stringData:
  password: "123123"

---
apiVersion: v1
kind: Secret
metadata:
  name: langfuse-s3-auth
type: Opaque
stringData:
  rootUser: "123123"
  rootPassword: "123123"
